### ISSUE TITLE
Warning about the log level `:warn` being deprecated

### ISSUE THREAD

**Issue by fmterrorf** [lexical-lsp/lexical#370]
I see the following output in the VSCode > Lexical logs 

```elixir
warning: the log level :warn is deprecated, use :warning instead
  (logger 1.15.5) lib/logger.ex:1137: Logger.elixir_level_to_erlang_level/1
  (logger 1.15.5) lib/logger.ex:591: Logger.compare_levels/2
  (logger_file_backend 0.0.13) lib/logger_file_backend.ex:36: LoggerFileBackend.handle_event/2
  (stdlib 5.0.2) gen_event.erl:802: :gen_event.server_update/4
  (stdlib 5.0.2) gen_event.erl:784: :gen_event.server_notify/4
  (stdlib 5.0.2) gen_event.erl:526: :gen_event.handle_msg/6
```

Erlang and Elixir version
```
elixir 1.15.5-otp-26
erlang 26.0.2
```

I'm using the Lexical VSCode extension, ran `mix package` and pointed the path override to `_build/dev/package/lexical/bin`

**Comment by scohen** [comment]
Note, this should be solved by adding --warnings-as-errors to ci

**Comment by scohen** [comment]
this should be fixed

**Comment by sardaukar** [comment]
Still seeing this on latest version (built from `main` right now, and path set on settings like previous comment):

```
2024-09-19 10:08:27.825 [info] [Trace - 10:08:27 AM] Received response 'textDocument/hover - (38)' in 7ms.
2024-09-19 10:08:35.120 [info] [Trace - 10:08:35 AM] Sending request 'textDocument/hover - (39)'.
2024-09-19 10:08:35.125 [info] warning: the log level :warn is deprecated, use :warning instead
  (logger 1.16.2) lib/logger.ex:1165: Logger.elixir_level_to_erlang_level/1
  (logger 1.16.2) lib/logger.ex:627: Logger.compare_levels/2
  (logger_file_backend 0.0.13) lib/logger_file_backend.ex:36: LoggerFileBackend.handle_event/2
  (stdlib 5.2.3) gen_event.erl:814: :gen_event.server_update/4
  (stdlib 5.2.3) gen_event.erl:796: :gen_event.server_notify/4
  (stdlib 5.2.3) gen_event.erl:538: :gen_event.handle_msg/6
```

Elixir 1.16.2-otp-26
Erlang 26.2.5
